"""
Django settings for password_gnerator project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # Место папки в которой находится наш проект и описание пути к ней

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gonamw8&xm0)gasdasdvsdfAAaAAAAA3i&&ep6vq1ap2hr_p6@f*r29c=0md5f$*f%+g'
# ключ доступа к нашему сайту и всей скрытой на нем информации
# ключ актуален только при онлайн доступе
# если его кто-то получит нам будет достаточно просто изменить его
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Индекатор режима откладки
# при значение True мы получаем от сайта куда больше информации, нежели когда он находится в режиме False
# когда мы работаем над проектом на локальном комьпютере то режим откладки должен быть включен, когда сайт выгружен
# в сеть то режим откладки должен быть выключен


ALLOWED_HOSTS = []

# Application definition
# компоненты которые будут использоваться нами при создании сайта
# наш сайт это весь проект в целом внутри которого содержаться одно или более приложений определяющих функционал сайта
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'generator',  # добавление приложения которое мы создали
]
# набор предустановок который более эфективно позволит использовать нам django
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# указывает на то где файл urls.py
ROOT_URLCONF = 'password_gnerator.urls'
# шаблоны позволяют денамически отображать HTML в браузире
# по сути суть серевера это вернуть HTML в браузер который его разберет и визеализирует для пользователя результат
# с помощью templates мы определяем каким образом наш HTML код должен быть визеалезирован браузером
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# настройка связаная с разворачиванием нашего сайта
WSGI_APPLICATION = 'password_gnerator.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# описание и адресс нашей базы данных которую мы используем для сайта
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # здесь указывается вручную имя базы данных
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
# ограничения для паролей к аккаунтам иющих доступ к сайту(как длина пароля или импользоапние доп символов)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
# настройки внешнего вида вэбсайта
LANGUAGE_CODE = 'en-us'  # язык

TIME_ZONE = 'UTC'  # тайм зон

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
